//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Stok_Proje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class TBLSAYFALAR
    {
        public int SAYFAID { get; set; }
        public string SAYFAAD { get; set; }


        
        [UIHint("tinymce_full_compressed"), AllowHtml]
        public string SAYFAYAZ { get; set; }



        public string SAYFAFOTO { get; set; }

    }
}
